### ISSUE TITLE
Support for utf8mb4 charset

### ISSUE THREAD

**Issue by DylanKeyer** [IaroslavR/scrapy-mysql-pipeline#8]
Database connection uses utf-8 charset with no override capabilities in Scrapy settings.py. Allowing for this override, for example, by MYSQL_CHARSET = '<charset>' would be very beneficial, especially when scraping content with emojis ('utf8mb4').

Thank you.

**Comment by qiuker521** [comment]
+1
important encoding

almost every site uses emoji

(simply copy the pipeline to my pipeline, then do change utf8 to utf8mb4 is well)

**Comment by IaroslavR** [comment]
closed in #11
